// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// src/app/layout.tsx
import '../styles/globals.css';
import { Poppins } from 'next/font/google';
import Navbar from '@/components/Navbar';


const poppins = Poppins({
subsets: ['latin'],
weight: ['300','400','500','600','700'],
variable: '--font-poppins'
});


export const metadata = {
title: 'ReUse! - Web',
description: 'Plataforma ReUse! - web',
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
return (
<html lang="pt-BR">
<body className={`${poppins.className} bg-reuse-neutral-100 text-reuse-neutral-900`}>
{/* If you have Instrument Sans font files, you can import them with next/font/local
and add its class name to the body. Example (uncomment and add font files):


import localInstrument from 'next/font/local'
const instrument = localInstrument({ src: [{ path: '/fonts/InstrumentSans-Regular.woff2', weight: '400' }, ...] })
<body className={`${instrument.className} ${poppins.className} ...`}>


*/}


<Navbar />
<main className="min-h-[80vh]">
{children}
</main>
<footer className="border-t border-gray-200 bg-white py-6">
<div className="container-reuse text-center text-sm text-gray-600">© {new Date().getFullYear()} ReUse! — Plataforma de Troca</div>
</footer>
</body>
</html>
);
}